[build-system]
requires = ["numpy", "setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
extend-exclude = '''
^/src/asammdf/gui/ui
'''

[tool.isort]
force_sort_within_sections = true
order_by_type = false
profile = "black"
skip_glob = ["src/asammdf/gui/ui"]

[tool.cibuildwheel]
test-requires = "pytest"
test-command = "pytest {project}/test"
build-frontend = "build"
archs = ["auto64"]  # only build for 64bit architectures
skip = "pp*"  # skip pypy