name: freeze_app

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: "recursive"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install linux libraries
        shell: bash
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt update
          sudo apt install libegl1 libopengl0

      - name: Install Python packages
        run: |
          pip install tox

      - name: Build with PyInstaller
        run: |
          tox -e pyinstaller -- --distpath dist/${{ matrix.os }} --noconfirm --clean

      - name: Archive PyInstaller artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pyinstaller-${{ matrix.os }}
          path: dist/${{ matrix.os }}/**
          if-no-files-found: error

      - name: Build with cx_Freeze
        run: |
          tox -e cxfreeze

      - name: Archive cx_Freeze artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cxFreeze-${{ matrix.os }}
          path: build/exe.*/**
          if-no-files-found: error
