name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        run: |
            pip install build numpy wheel nuitka
            pip install -r requirements_exe_build.txt
            python setup.py bdist_wheel
            pip install -e . --no-deps
            pip install cmerg

      - name: Build an executable
        shell: bash
        if: ${{ matrix.python-version == '3.10' }}
        run: |
            if [ "$RUNNER_OS" == "Linux" ]; then
                 sudo apt update
                 sudo apt install libegl1 libopengl0
            fi
            python -m nuitka ./src/asammdf/gui/asammdfgui.py --standalone --enable-plugin=numpy --enable-plugin=pyside6 --disable-console
            cp asammdfd.dist dist/${RUNNER_OS}

      # see: https://docs.github.com/en/actions/advanced-guides/storing-workflow-data-as-artifacts
      - name: Archive dist artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/**
          if-no-files-found: error
